### ISSUE TITLE
Differentiation of simple operations

### ISSUE THREAD

**Issue by alexgian** [littleredcomputer/sicmutils#14]
Differentiation of simple operations (+, -, x) should be permitted, as per MIT scmutils:
```
1 ]=> ((D +)'x 'y)
#|
(down 1 1)
|#
```

**Comment by alexgian** [comment]
Also, differentiation of expt isn't quite right yet, even though it now works for literal-functions
```
9 error> ((D expt)'x 'y)    ;;; Scmutils
#|
(down (* y (expt x (+ -1 y))) (* (expt x y) (log x)))
|#
```
but sicmutils:
```
sicmutils.env=> ((D expt)'x 'y)
ArityException Wrong number of args (2) passed to: derivative/euclidean-structure/a-euclidean-derivative--1307  clojure.lang.AFn.throwArity (AFn.java:429)
```

**Comment by alexgian** [comment]
OK, that last example of pow, using apply and repeat, is a bit of a gyp, it doesn't work under scmutils either, using (makelist n x) instead of (repeat n x).
I'm not sure whether it's "apply" that's bothering it, or maybe even "repeat" - or just the number of arguments.

I was quite surprised when I first discovered that differentiation could even work *at all* on higher-order functions, like that old example
```
> (def unity (reduce + (map (square [sin cos]))))
> ((D unity) 2)
0
```
However, I think that *something* does need attention, because if I define pow using a recursive function "copies"
```
[sicmutils.env] > (defn copies [n x] (if (= n 0) nil (cons x (copies (- n 1) x))))
[sicmutils.env] > (copies 3 5)     ==>  (5 5 5)
[sicmutils.env] > (defn pow [a x] (reduce * (copies x a)))
[sicmutils.env] > ((D pow) 2 3)

StackOverflowError   clojure.lang.RT.seqFrom (RT.java:514)
```
It should at least work on simple recursive definitions should it not?
I also tried using this, in case it didn't like plain vanilla recursion, but to no avail.
```
[sicmutils.env] > (defn copies ([n x] (copies n x nil))([n x a] (if (= n 0) a (copies (- n 1) x (cons x a)))))
[sicmutils.env] > (defn pow [a x](reduce * (copies x a)))
[sicmutils.env] > (pow 3 4) ==> 81
[sicmutils.env] > ((D pow) 3 4)

StackOverflowError   clojure.lang.RT.seqFrom (RT.java:514)
```
I would think that an operation composed of any simple differentiable (euclidian) functions should differentiate, but this is not very high up on my priority list, as I can't get it to work under scmutils, either.  
```
9 error> (define (pow a x) (reduce-left * 1 (make-list x a)))
#| pow |#
9 error> (pow 3 4)
#| 81 |#
9 error> ((D pow) 'x 'y)

;The object y, passed as an argument to make-list, is not an index integer.
;To continue, call RESTART with an option number:
;; [...]
10 error> ((D pow) 3 4)

;The object (*diff* (() 4) ((5) 1)), passed as an argument to make-list, is not an index integer.
;To continue, call RESTART with an option number:
;; [...]
11 error> 
```
I haven't looked at the code yet, but I suspect the proble is with what arguments get accepted.
I'd definitely make a note for the future on this one, though...

**Comment by littleredcomputer** [comment]
All these problems will be fixed shortly except for the ones involving "repeat" and "copies." The trick with them is that at some point they will require a genuine integer to work.

The way differentiation works in s(i)cmutils, is that a "differential quantity": the code equivalent of say, 3 + epsilon, is being sent into the function, so we can see the change that produces over the value of the function at the plain value 3. There's no way to get "repeat" to make a list of length 3+epsilon, so we can't make a homebrew pow that works.

Under the hood, each generic function knows its own derivative (*), so when sin sees x+epsilon it knows that what should come out is cos(epsilon). (But then you'll have seen all this since you've been reading up on forward automatic differentiation).

(*) So there are going to be functions that s(i)cmutils knows that are problematic, like `abs`. We punt them; this is a difference between this system and something that works harder, like Mathematica; we're constrained to live in the world of well-behaved functions if we are going to exploit the calculus capability
