### ISSUE TITLE
2nd partial derivative of literal function

### ISSUE THREAD

**Issue by alexgian** [littleredcomputer/sicmutils#18]
```
> (def ff (literal-function 'ff [0 0] 0))
> (((* D D) ff) 'x 'y)        ;; great, no problems
(down
 (down (((∂ 0) ((∂ 0) ff)) x y) (((∂ 0) ((∂ 1) ff)) x y))
 (down (((∂ 1) ((∂ 0) ff)) x y) (((∂ 1) ((∂ 1) ff)) x y))) 
> (((* (partial 1) (partial 0)) ff) 'x 'y)  ;; composition of partials, even better
(((∂ 1) ((∂ 0) ff)) x y)
```
but plain invocation via selectors...
```
> (((partial 1 0) ff) 'x 'y)    ;; ........erm?
IllegalArgumentException No implementation of method: :numerical? of protocol: #'sicmutils.value/Value found for class: nil  clojure.core/-cache-protocol-fn (core_deftype.clj:554)
```

**Comment by alexgian** [comment]
Broken because of the shimming?  I think yYou mentioned testing on number of arguments, can't remember exactly, tbh.

If so, perhaps we could just test if first argument is an integer or a function?

**Comment by littleredcomputer** [comment]
I got tripped up by this too. `(partial 0 1)` is not the composition of `(partial 0)` and `(partial 1)`. It is the partial with resepect to the second element of the first slot of the function (or the first slot of the zero'th slot if we count from zero). Since `f` does not have two layers of structure, the attempt to reference the (0,1) element bottoms out with a null as we try to find it. (See: p. 500, or p. 497 in the PDF).

But as I look I find that I have no unit tests for this! That's bad. I'll fix that before closing.

Furthermore, the error message is awful.
