### ISSUE TITLE
Make "vector" its own thing, instead of a subtype of an up tuple?

### ISSUE THREAD

**Issue by sritchie** [littleredcomputer/sicmutils#192]
in `scmutils`, a vector is its own special type. @littleredcomputer , it seemed to me when I was studying this that a vector was ALWAYS an up tuple - is that the case? It might be nice to implement the generics in a way that keeps vectors as vectors, instead of converting them to tuples.

Would love thoughts here.

**Comment by littleredcomputer** [comment]
I went back and forth on this. I tried vectors with metadata, but that fell
apart because a lot of things produce seqs. My philosophy was "anything
seq-like is UP where an orientation is demanded" and I think this is what
scmutils intended.

It might make sense to have an orientation-less vector type... but don't we
also want (* d u) to be dot-product when d is "officially" down but u is
perhaps unspecified?

a good topic. what motivates this on your side?

Put another way, if we renamed ::up to ::vector, in what way would that
_not_ achieve what you wanted?

**Comment by sritchie** [comment]
I think you've confirmed my suspicion, that vector was a first attempt and `up` replaced it. As I look at the code more closely I see that many of the vector implementations are commented out, with `up` installed instead. And of course `up?` simply aliases `vector?`.

So, no need to go down this path! These light deftype wrappers are cheap and quite appropriate for installing behavior we care about.
