### ISSUE TITLE
A couple of issues here  (D cot)

### ISSUE THREAD

**Issue by alexgian** [littleredcomputer/sicmutils#23]
I've included both issues here, probably should make two separate issues, sorry...

First, 
```
[sicmutils.env] > (defn cot [x] (/ 1 (tan x)))
cot
[sicmutils.env] > ((D cot)'x)
(/ -1 (* (expt (tan x) 2) (expt (cos x) 2)))
```
The simplifier is lagging a bit here, yes?
scmutils gives a somewhat better
```
1 ]=> ((D cot) 'x)
#|
(/ -1 (expt (sin x) 2))
|#
```
We also find other similar fruity examples, such as:
```
[sicmutils.env] > ((D (/ cos sin)) 'x)
(/ 1 (+ (expt (cos x) 2) -1))
```
They're not *wrong*, of course, but their simplification might be a bit more elegant.

======

Secondly, when we get to the generated TeX code, we get:
```
$$\dfrac-1{{\tan\left(x\right)}^2\,{\cos\left(x\right)}^2}$$
```
Which gives a bit of a garbled result.
see here:
http://aegean.pwp.blueyonder.co.uk/images/cool/eclipse2.png

I suspect something like the following would fix it a bit
```
$$\dfrac{-1}{{\tan\left(x\right)}^2\,{\cos\left(x\right)}^2}$$
```
At least it does on the Gorilla-REPL renderer which I'm using to check.

**Comment by littleredcomputer** [comment]
Two great issues!

There are a lot of rules in scmutils that I haven't ported over yet ... basically because I want to see them work and provide unit tests for them before importing them blindly. Partially this was motivated by fear of a large & complex system. I'll fix this one. You're right about dfrac as well so I'll fix 'em together.
